<template>
  <v-card>
    <v-card-title>
      <span class="ammo-title"
        >EFT 弾薬諸元表 <span class="patch-version">Patch 0.12</span></span
      >
      <v-spacer></v-spacer>
      <v-text-field
        v-model="search"
        append-icon="mdi-magnify"
        label="検索"
        single-line
        hide-details
      ></v-text-field>
    </v-card-title>
    <v-data-table
      :headers="headers"
      :items="ammo"
      :items-per-page="ammo.length"
      :search="search"
      hide-default-footer
      class="elevation-1"
    ></v-data-table>
  </v-card>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

@Component
export default class Ammunition extends Vue {
  search = "";
  headers = [
    { text: "弾薬", value: "ammo" },
    { text: "重量 [kg]", value: "weight" },
    { text: "値段 [₽]", value: "price" },
    { text: "ダメージ", value: "damage" },
    { text: "精度 [%]", value: "accuracy" },
    { text: "反動 [%]", value: "recoil" },
    { text: "貫通値", value: "penetrationValue" },
    { text: "弾体数", value: "projectileCount" },
    { text: "初速 [m/s]", value: "projectileSpeed" },
    { text: "貫通率", value: "penetrationChance" },
    { text: "跳弾率", value: "ricochetChance" },
    { text: "破砕率", value: "fragmentationChance" },
    { text: "アーマー損傷率", value: "armorDamage" }
  ];
  ammo = [
    {
      ammo: "12.7x108mm B-32",
      weight: "0.133",
      price: "820",
      damage: "182",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "88",
      projectileCount: "1",
      projectileSpeed: "818",
      penetrationChance: "0.75",
      ricochetChance: "0.38",
      fragmentationChance: "0.17",
      armorDamage: "88"
    },
    {
      ammo: "12.7x108mm BZT-44M",
      weight: "0.128",
      price: "980",
      damage: "199",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "80",
      projectileCount: "1",
      projectileSpeed: "818",
      penetrationChance: "0.75",
      ricochetChance: "0.38",
      fragmentationChance: "0.17",
      armorDamage: "95"
    },
    {
      ammo: "12.7x55mm PS12",
      weight: "0.07",
      price: "340",
      damage: "115",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "25",
      projectileCount: "1",
      projectileSpeed: "285",
      penetrationChance: "0.6",
      ricochetChance: "0.4",
      fragmentationChance: "0.3",
      armorDamage: "60"
    },
    {
      ammo: "12.7x55mm PS12A",
      weight: "0.044",
      price: "280",
      damage: "155",
      accuracy: "-15",
      recoil: "7",
      penetrationValue: "8",
      projectileCount: "1",
      projectileSpeed: "290",
      penetrationChance: "0.1",
      ricochetChance: "0.2",
      fragmentationChance: "0.7",
      armorDamage: "17"
    },
    {
      ammo: "12.7x55mm PS12B",
      weight: "0.055",
      price: "455",
      damage: "90",
      accuracy: "0",
      recoil: "15",
      penetrationValue: "40",
      projectileCount: "1",
      projectileSpeed: "300",
      penetrationChance: "0.8",
      ricochetChance: "0.65",
      fragmentationChance: "0.3",
      armorDamage: "57"
    },
    {
      ammo: "12/70 7mm Buckshot",
      weight: "0.05",
      price: "30",
      damage: "32",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "3",
      projectileCount: "8",
      projectileSpeed: "415",
      penetrationChance: "0.02",
      ricochetChance: "0",
      fragmentationChance: "0",
      armorDamage: "26"
    },
    {
      ammo: "12/70 5.25mm Buckshot",
      weight: "0.044",
      price: "35",
      damage: "17",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "1",
      projectileCount: "15",
      projectileSpeed: "330",
      penetrationChance: "0.02",
      ricochetChance: "0",
      fragmentationChance: "0",
      armorDamage: "15"
    },
    {
      ammo: '12/70 6.5mm "Express" Buckshot',
      weight: "0.048",
      price: "39",
      damage: "29",
      accuracy: "15",
      recoil: "0",
      penetrationValue: "3",
      projectileCount: "9",
      projectileSpeed: "430",
      penetrationChance: "0.02",
      ricochetChance: "0",
      fragmentationChance: "0",
      armorDamage: "26"
    },
    {
      ammo: '12/70 8.5mm "Magnum" Buckshot',
      weight: "0.059",
      price: "50",
      damage: "22",
      accuracy: "-15",
      recoil: "115",
      penetrationValue: "2",
      projectileCount: "16",
      projectileSpeed: "385",
      penetrationChance: "0.05",
      ricochetChance: "0",
      fragmentationChance: "0",
      armorDamage: "26"
    },
    {
      ammo: "12/70 Dual Sabot Slug",
      weight: "0.05",
      price: "68",
      damage: "75",
      accuracy: "100",
      recoil: "15",
      penetrationValue: "17",
      projectileCount: "2",
      projectileSpeed: "415",
      penetrationChance: "0.25",
      ricochetChance: "0.1",
      fragmentationChance: "0.1",
      armorDamage: "65"
    },
    {
      ammo: "12/70 Flechette",
      weight: "0.04",
      price: "75",
      damage: "19",
      accuracy: "-25",
      recoil: "0",
      penetrationValue: "28",
      projectileCount: "8",
      projectileSpeed: "320",
      penetrationChance: "0.3",
      ricochetChance: "0",
      fragmentationChance: "0",
      armorDamage: "26"
    },
    {
      ammo: "12/70 RIP",
      weight: "0.04",
      price: "302",
      damage: "235",
      accuracy: "80",
      recoil: "35",
      penetrationValue: "0",
      projectileCount: "1",
      projectileSpeed: "410",
      penetrationChance: "0",
      ricochetChance: "0.01",
      fragmentationChance: "1",
      armorDamage: "11"
    },
    {
      ammo: "12/70 Led slug",
      weight: "0.05",
      price: "56",
      damage: "147",
      accuracy: "100",
      recoil: "0",
      penetrationValue: "15",
      projectileCount: "1",
      projectileSpeed: "370",
      penetrationChance: "0.2",
      ricochetChance: "0.1",
      fragmentationChance: "0.2",
      armorDamage: "45"
    },
    {
      ammo: "12/70 shell with .50 BMG bullet",
      weight: "0.055",
      price: "124",
      damage: "177",
      accuracy: "90",
      recoil: "25",
      penetrationValue: "23",
      projectileCount: "1",
      projectileSpeed: "410",
      penetrationChance: "0.28",
      ricochetChance: "0.1",
      fragmentationChance: "0.05",
      armorDamage: "57"
    },
    {
      ammo: "12/70 AP-20 Slug",
      weight: "0.05",
      price: "137",
      damage: "164",
      accuracy: "125",
      recoil: "50",
      penetrationValue: "32",
      projectileCount: "1",
      projectileSpeed: "510",
      penetrationChance: "0.36",
      ricochetChance: "0.1",
      fragmentationChance: "0.03",
      armorDamage: "65"
    },
    {
      ammo: "12/70 FTX Custom LIte Slug",
      weight: "0.026",
      price: "71",
      damage: "153",
      accuracy: "115",
      recoil: "0",
      penetrationValue: "18",
      projectileCount: "1",
      projectileSpeed: "480",
      penetrationChance: "0.28",
      ricochetChance: "0.1",
      fragmentationChance: "0.1",
      armorDamage: "50"
    },
    {
      ammo: "12/70 Grizzly 40 Slug",
      weight: "0.055",
      price: "66",
      damage: "170",
      accuracy: "80",
      recoil: "20",
      penetrationValue: "12",
      projectileCount: "1",
      projectileSpeed: "390",
      penetrationChance: "0.2",
      ricochetChance: "0.1",
      fragmentationChance: "0.12",
      armorDamage: "48"
    },
    {
      ammo: "12/70 HP Slug Copper Sabot Premier",
      weight: "0.043",
      price: "82",
      damage: "160",
      accuracy: "150",
      recoil: "10",
      penetrationValue: "13",
      projectileCount: "1",
      projectileSpeed: "442",
      penetrationChance: "0.22",
      ricochetChance: "0.1",
      fragmentationChance: "0.38",
      armorDamage: "46"
    },
    {
      ammo: '12/70 "Poleva-3" Slug',
      weight: "0.044",
      price: "51",
      damage: "130",
      accuracy: "90",
      recoil: "-15",
      penetrationValue: "17",
      projectileCount: "1",
      projectileSpeed: "410",
      penetrationChance: "0.17",
      ricochetChance: "0.1",
      fragmentationChance: "0.2",
      armorDamage: "40"
    },
    {
      ammo: '12/70 "Poleva-6u" Slug',
      weight: "0.048",
      price: "68",
      damage: "140",
      accuracy: "95",
      recoil: "-10",
      penetrationValue: "20",
      projectileCount: "1",
      projectileSpeed: "430",
      penetrationChance: "0.2",
      ricochetChance: "0.1",
      fragmentationChance: "0.15",
      armorDamage: "50"
    },
    {
      ammo: '12/70 HP Slug "SuperFormance"',
      weight: "0.034",
      price: "192",
      damage: "190",
      accuracy: "140",
      recoil: "-15",
      penetrationValue: "2",
      projectileCount: "1",
      projectileSpeed: "594",
      penetrationChance: "0.05",
      ricochetChance: "0.1",
      fragmentationChance: "0.39",
      armorDamage: "12"
    },
    {
      ammo: "20/70 7.5mm Buckshot",
      weight: "0.04",
      price: "24",
      damage: "20",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "3",
      projectileCount: "8",
      projectileSpeed: "430",
      penetrationChance: "0.02",
      ricochetChance: "0",
      fragmentationChance: "0",
      armorDamage: "14"
    },
    {
      ammo: "20/70 5.6mm Buckshot",
      weight: "0.028",
      price: "20",
      damage: "11",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "1",
      projectileCount: "15",
      projectileSpeed: "340",
      penetrationChance: "0.02",
      ricochetChance: "0",
      fragmentationChance: "0",
      armorDamage: "12"
    },
    {
      ammo: "20/70 6.2mm Buckshot",
      weight: "0.032",
      price: "30",
      damage: "14",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "2",
      projectileCount: "12",
      projectileSpeed: "410",
      penetrationChance: "0.02",
      ricochetChance: "0",
      fragmentationChance: "0",
      armorDamage: "13"
    },
    {
      ammo: "20/70 7.3mm Buckshot",
      weight: "0.032",
      price: "38",
      damage: "22",
      accuracy: "0",
      recoil: "15",
      penetrationValue: "3",
      projectileCount: "9",
      projectileSpeed: "475",
      penetrationChance: "0.02",
      ricochetChance: "0",
      fragmentationChance: "0",
      armorDamage: "13"
    },
    {
      ammo: "20/70 Devastator Slug",
      weight: "0.029",
      price: "180",
      damage: "188",
      accuracy: "115",
      recoil: "30",
      penetrationValue: "4",
      projectileCount: "1",
      projectileSpeed: "405",
      penetrationChance: "0.05",
      ricochetChance: "0.1",
      fragmentationChance: "1",
      armorDamage: "13"
    },
    {
      ammo: '20/70 Slug "Poleva-"',
      weight: "0.029",
      price: "48",
      damage: "110",
      accuracy: "90",
      recoil: "-15",
      penetrationValue: "14",
      projectileCount: "1",
      projectileSpeed: "425",
      penetrationChance: "0.15",
      ricochetChance: "0.1",
      fragmentationChance: "0.2",
      armorDamage: "35"
    },
    {
      ammo: "20/70 Slug Poleva-6u",
      weight: "0.032",
      price: "65",
      damage: "120",
      accuracy: "95",
      recoil: "-10",
      penetrationValue: "17",
      projectileCount: "1",
      projectileSpeed: "445",
      penetrationChance: "0.2",
      ricochetChance: "0.1",
      fragmentationChance: "0.15",
      armorDamage: "40"
    },
    {
      ammo: "20/70 Star Slug",
      weight: "0.034",
      price: "81",
      damage: "134",
      accuracy: "100",
      recoil: "0",
      penetrationValue: "16",
      projectileCount: "1",
      projectileSpeed: "415",
      penetrationChance: "0.17",
      ricochetChance: "0.1",
      fragmentationChance: "0.1",
      armorDamage: "42"
    },
    {
      ammo: ".366 ТКМ EKO",
      weight: "0.016",
      price: "85",
      damage: "65",
      accuracy: "-10",
      recoil: "0",
      penetrationValue: "26",
      projectileCount: "1",
      projectileSpeed: "770",
      penetrationChance: "0.15",
      ricochetChance: "0.1",
      fragmentationChance: "0.2",
      armorDamage: "38"
    },
    {
      ammo: ".366 ТКМ FMJ",
      weight: "0.016",
      price: "42",
      damage: "71",
      accuracy: "0",
      recoil: "10",
      penetrationValue: "20",
      projectileCount: "1",
      projectileSpeed: "580",
      penetrationChance: "0.12",
      ricochetChance: "0.065",
      fragmentationChance: "0.25",
      armorDamage: "36"
    },
    {
      ammo: ".366 ТКМ Geksa",
      weight: "0.016",
      price: "57",
      damage: "77",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "14",
      projectileCount: "1",
      projectileSpeed: "550",
      penetrationChance: "0.12",
      ricochetChance: "0.05",
      fragmentationChance: "0.45",
      armorDamage: "38"
    },
    {
      ammo: "4.6x30mm Action SX",
      weight: "0.007",
      price: "98",
      damage: "65",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "13",
      projectileCount: "1",
      projectileSpeed: "690",
      penetrationChance: "0.2",
      ricochetChance: "0.3",
      fragmentationChance: "0.5",
      armorDamage: "39"
    },
    {
      ammo: "4.6x30mm AP SX",
      weight: "0.007",
      price: "255",
      damage: "35",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "47",
      projectileCount: "1",
      projectileSpeed: "680",
      penetrationChance: "0.6",
      ricochetChance: "0.6",
      fragmentationChance: "0.1",
      armorDamage: "46"
    },
    {
      ammo: "4.6x30mm FMJ SX",
      weight: "0.007",
      price: "124",
      damage: "43",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "30",
      projectileCount: "1",
      projectileSpeed: "620",
      penetrationChance: "0.4",
      ricochetChance: "0.4",
      fragmentationChance: "0.2",
      armorDamage: "41"
    },
    {
      ammo: "4.6x30mm Subsonic SX",
      weight: "0.01",
      price: "162",
      damage: "41",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "34",
      projectileCount: "1",
      projectileSpeed: "290",
      penetrationChance: "0.3",
      ricochetChance: "0.5",
      fragmentationChance: "0.2",
      armorDamage: "46"
    },
    {
      ammo: '5.45x39mm 7N39 "Igolnik"',
      weight: "0.011",
      price: "562",
      damage: "37",
      accuracy: "0",
      recoil: "15",
      penetrationValue: "62",
      projectileCount: "1",
      projectileSpeed: "905",
      penetrationChance: "0.8",
      ricochetChance: "0.38",
      fragmentationChance: "0.02",
      armorDamage: "60"
    },
    {
      ammo: "5.45x39mm BP",
      weight: "0.01",
      price: "129",
      damage: "42",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "32",
      projectileCount: "1",
      projectileSpeed: "890",
      penetrationChance: "0.72",
      ricochetChance: "0.36",
      fragmentationChance: "0.16",
      armorDamage: "38"
    },
    {
      ammo: "5.45x39mm BS",
      weight: "0.01",
      price: "380",
      damage: "40",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "50",
      projectileCount: "1",
      projectileSpeed: "830",
      penetrationChance: "0.75",
      ricochetChance: "0.38",
      fragmentationChance: "0.17",
      armorDamage: "57"
    },
    {
      ammo: "5.45x39mm BT",
      weight: "0.01",
      price: "240",
      damage: "44",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "33",
      projectileCount: "1",
      projectileSpeed: "880",
      penetrationChance: "0.66",
      ricochetChance: "0.37",
      fragmentationChance: "0.164",
      armorDamage: "52"
    },
    {
      ammo: "5.45x39mm FMJ",
      weight: "0.01",
      price: "36",
      damage: "54",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "18",
      projectileCount: "1",
      projectileSpeed: "884",
      penetrationChance: "0.51",
      ricochetChance: "0.26",
      fragmentationChance: "0.25",
      armorDamage: "44"
    },
    {
      ammo: "5.45x39mm HP",
      weight: "0.01",
      price: "68",
      damage: "73",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "11",
      projectileCount: "1",
      projectileSpeed: "884",
      penetrationChance: "0.48",
      ricochetChance: "0.2",
      fragmentationChance: "0.35",
      armorDamage: "32"
    },
    {
      ammo: "5.45x39mm PP",
      weight: "0.01",
      price: "108",
      damage: "46",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "27",
      projectileCount: "1",
      projectileSpeed: "890",
      penetrationChance: "0.66",
      ricochetChance: "0.38",
      fragmentationChance: "0.17",
      armorDamage: "50"
    },
    {
      ammo: "5.45x39mm PRS",
      weight: "0.01",
      price: "46",
      damage: "60",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "14",
      projectileCount: "1",
      projectileSpeed: "890",
      penetrationChance: "0.51",
      ricochetChance: "0.04",
      fragmentationChance: "0.3",
      armorDamage: "34"
    },
    {
      ammo: "5.45x39mm PS",
      weight: "0.01",
      price: "74",
      damage: "50",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "23",
      projectileCount: "1",
      projectileSpeed: "890",
      penetrationChance: "0.7",
      ricochetChance: "0.4",
      fragmentationChance: "0.4",
      armorDamage: "47"
    },
    {
      ammo: "5.45x39mm SP",
      weight: "0.01",
      price: "60",
      damage: "68",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "11",
      projectileCount: "1",
      projectileSpeed: "873",
      penetrationChance: "0.4",
      ricochetChance: "0.15",
      fragmentationChance: "0.45",
      armorDamage: "34"
    },
    {
      ammo: "5.45x39mm T",
      weight: "0.01",
      price: "40",
      damage: "57",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "20",
      projectileCount: "1",
      projectileSpeed: "883",
      penetrationChance: "0.54",
      ricochetChance: "0.4",
      fragmentationChance: "0.16",
      armorDamage: "38"
    },
    {
      ammo: "5.45x39mm US",
      weight: "0.01",
      price: "79",
      damage: "65",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "15",
      projectileCount: "1",
      projectileSpeed: "303",
      penetrationChance: "0.45",
      ricochetChance: "0.4",
      fragmentationChance: "0.1",
      armorDamage: "34"
    },
    {
      ammo: "5.56x45mm 55 FMJ",
      weight: "0.012",
      price: "85",
      damage: "52",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "24",
      projectileCount: "1",
      projectileSpeed: "957",
      penetrationChance: "0.425",
      ricochetChance: "0.26",
      fragmentationChance: "0.5",
      armorDamage: "45"
    },
    {
      ammo: "5.56x45mm 55 HP",
      weight: "0.012",
      price: "58",
      damage: "72",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "9",
      projectileCount: "1",
      projectileSpeed: "947",
      penetrationChance: "0.4",
      ricochetChance: "0.2",
      fragmentationChance: "0.7",
      armorDamage: "38"
    },
    {
      ammo: "5.56x45mm M855",
      weight: "0.012",
      price: "110",
      damage: "50",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "26",
      projectileCount: "1",
      projectileSpeed: "922",
      penetrationChance: "0.5",
      ricochetChance: "0.4",
      fragmentationChance: "0.4",
      armorDamage: "40"
    },
    {
      ammo: "5.56x45mm M855A1",
      weight: "0.012",
      price: "142",
      damage: "57",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "31",
      projectileCount: "1",
      projectileSpeed: "945",
      penetrationChance: "0.55",
      ricochetChance: "0.38",
      fragmentationChance: "0.34",
      armorDamage: "42"
    },
    {
      ammo: "5.56x45mm M856",
      weight: "0.012",
      price: "128",
      damage: "55",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "23",
      projectileCount: "1",
      projectileSpeed: "874",
      penetrationChance: "0.55",
      ricochetChance: "0.38",
      fragmentationChance: "0.328",
      armorDamage: "38"
    },
    {
      ammo: "5.56x45mm M856A1",
      weight: "0.012",
      price: "182",
      damage: "56",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "34",
      projectileCount: "1",
      projectileSpeed: "940",
      penetrationChance: "0.55",
      ricochetChance: "0.38",
      fragmentationChance: "0.328",
      armorDamage: "45"
    },
    {
      ammo: "5.56x45mm M995",
      weight: "0.012",
      price: "345",
      damage: "42",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "53",
      projectileCount: "1",
      projectileSpeed: "1013",
      penetrationChance: "0.6",
      ricochetChance: "0.36",
      fragmentationChance: "0.32",
      armorDamage: "57"
    },
    {
      ammo: "5.56x45mm Mk 255 Mod 0",
      weight: "0.012",
      price: "135",
      damage: "60",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "17",
      projectileCount: "1",
      projectileSpeed: "936",
      penetrationChance: "0.2",
      ricochetChance: "0.1",
      fragmentationChance: "0.03",
      armorDamage: "32"
    },
    {
      ammo: "5.56x45mm Warmage",
      weight: "0.011",
      price: "156",
      damage: "83",
      accuracy: "10",
      recoil: "10",
      penetrationValue: "3",
      projectileCount: "1",
      projectileSpeed: "910",
      penetrationChance: "0.2",
      ricochetChance: "0.05",
      fragmentationChance: "0.9",
      armorDamage: "14"
    },
    {
      ammo: "5.7x28mm L191",
      weight: "0.006",
      price: "112",
      damage: "58",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "33",
      projectileCount: "1",
      projectileSpeed: "716",
      penetrationChance: "0.5",
      ricochetChance: "0.6",
      fragmentationChance: "0.2",
      armorDamage: "41"
    },
    {
      ammo: "5.7x28mm R37.F",
      weight: "0.006",
      price: "215",
      damage: "98",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "8",
      projectileCount: "1",
      projectileSpeed: "729",
      penetrationChance: "0.02",
      ricochetChance: "0.05",
      fragmentationChance: "1",
      armorDamage: "7"
    },
    {
      ammo: "5.7x28mm R37.X",
      weight: "0.006",
      price: "186",
      damage: "81",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "11",
      projectileCount: "1",
      projectileSpeed: "724",
      penetrationChance: "0.15",
      ricochetChance: "0.1",
      fragmentationChance: "0.7",
      armorDamage: "14"
    },
    {
      ammo: "5.7x28mm SB193",
      weight: "0.007",
      price: "143",
      damage: "54",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "37",
      projectileCount: "1",
      projectileSpeed: "305",
      penetrationChance: "0.5",
      ricochetChance: "0.3",
      fragmentationChance: "0.2",
      armorDamage: "47"
    },
    {
      ammo: "5.7x28mm SS190",
      weight: "0.006",
      price: "105",
      damage: "57",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "32",
      projectileCount: "1",
      projectileSpeed: "716",
      penetrationChance: "0.5",
      ricochetChance: "0.6",
      fragmentationChance: "0.2",
      armorDamage: "43"
    },
    {
      ammo: "5.7x28mm SS197SR",
      weight: "0.007",
      price: "110",
      damage: "62",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "20",
      projectileCount: "1",
      projectileSpeed: "594",
      penetrationChance: "0.2",
      ricochetChance: "0.2",
      fragmentationChance: "0.5",
      armorDamage: "22"
    },
    {
      ammo: "5.7x28mm SS198LF",
      weight: "0.006",
      price: "134",
      damage: "74",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "10",
      projectileCount: "1",
      projectileSpeed: "792",
      penetrationChance: "0.1",
      ricochetChance: "0.2",
      fragmentationChance: "0.8",
      armorDamage: "15"
    },
    {
      ammo: "7.62x25mm TT FMJ43",
      weight: "0.01",
      price: "50",
      damage: "60",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "8",
      projectileCount: "1",
      projectileSpeed: "427",
      penetrationChance: "0.17",
      ricochetChance: "0.065",
      fragmentationChance: "0.25",
      armorDamage: "29"
    },
    {
      ammo: "7.62x25mm TT LRN",
      weight: "0.01",
      price: "48",
      damage: "64",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "6",
      projectileCount: "1",
      projectileSpeed: "375",
      penetrationChance: "0.16",
      ricochetChance: "0.05",
      fragmentationChance: "0.35",
      armorDamage: "28"
    },
    {
      ammo: "7.62x25mm TT LRNPC",
      weight: "0.01",
      price: "68",
      damage: "66",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "5",
      projectileCount: "1",
      projectileSpeed: "385",
      penetrationChance: "0.16",
      ricochetChance: "0.05",
      fragmentationChance: "0.35",
      armorDamage: "27"
    },
    {
      ammo: "7.62x25mm TT P gl",
      weight: "0.01",
      price: "52",
      damage: "58",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "10",
      projectileCount: "1",
      projectileSpeed: "430",
      penetrationChance: "0.17",
      ricochetChance: "0.065",
      fragmentationChance: "0.25",
      armorDamage: "32"
    },
    {
      ammo: "7.62x25mm TT Pst gzh",
      weight: "0.01",
      price: "70",
      damage: "50",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "19",
      projectileCount: "1",
      projectileSpeed: "430",
      penetrationChance: "0.2",
      ricochetChance: "0.1",
      fragmentationChance: "0.2",
      armorDamage: "36"
    },
    {
      ammo: "7.62x25mm TT PT gzh",
      weight: "0.01",
      price: "63",
      damage: "60",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "12",
      projectileCount: "1",
      projectileSpeed: "415",
      penetrationChance: "0.18",
      ricochetChance: "0.1",
      fragmentationChance: "0.166",
      armorDamage: "34"
    },
    {
      ammo: "7.62x25mm TT AKBS",
      weight: "0.01",
      price: "49",
      damage: "58",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "9",
      projectileCount: "1",
      projectileSpeed: "425",
      penetrationChance: "0.17",
      ricochetChance: "0.065",
      fragmentationChance: "0.25",
      armorDamage: "32"
    },
    {
      ammo: "7.62x39mm BP",
      weight: "0.01",
      price: "299",
      damage: "50",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "45",
      projectileCount: "1",
      projectileSpeed: "730",
      penetrationChance: "0.84",
      ricochetChance: "0.315",
      fragmentationChance: "0.12",
      armorDamage: "65"
    },
    {
      ammo: "7.62x39mm HP",
      weight: "0.016",
      price: "60",
      damage: "76",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "15",
      projectileCount: "1",
      projectileSpeed: "754",
      penetrationChance: "0.56",
      ricochetChance: "0.175",
      fragmentationChance: "0.2625",
      armorDamage: "45"
    },
    {
      ammo: "7.62x39mm PS",
      weight: "0.016",
      price: "83",
      damage: "57",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "33",
      projectileCount: "1",
      projectileSpeed: "700",
      penetrationChance: "0.8",
      ricochetChance: "0.35",
      fragmentationChance: "0.25",
      armorDamage: "50"
    },
    {
      ammo: "7.62x39mm T45M",
      weight: "0.01",
      price: "58",
      damage: "58",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "26",
      projectileCount: "1",
      projectileSpeed: "720",
      penetrationChance: "0.63",
      ricochetChance: "0.35",
      fragmentationChance: "0.12",
      armorDamage: "48"
    },
    {
      ammo: "7.62x39mm US",
      weight: "0.01",
      price: "134",
      damage: "68",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "19",
      projectileCount: "1",
      projectileSpeed: "300",
      penetrationChance: "0.52",
      ricochetChance: "0.358",
      fragmentationChance: "0.075",
      armorDamage: "41"
    },
    {
      ammo: "7.62x51mm M61",
      weight: "0.024",
      price: "390",
      damage: "70",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "68",
      projectileCount: "1",
      projectileSpeed: "849",
      penetrationChance: "0.9",
      ricochetChance: "0.3",
      fragmentationChance: "0.13",
      armorDamage: "83"
    },
    {
      ammo: "7.62x51mm M62",
      weight: "0.024",
      price: "275",
      damage: "79",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "54",
      projectileCount: "1",
      projectileSpeed: "816",
      penetrationChance: "0.67",
      ricochetChance: "0.38",
      fragmentationChance: "0.14",
      armorDamage: "75"
    },
    {
      ammo: "7.62x51mm M80",
      weight: "0.024",
      price: "178",
      damage: "80",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "45",
      projectileCount: "1",
      projectileSpeed: "833",
      penetrationChance: "0.75",
      ricochetChance: "0.38",
      fragmentationChance: "0.17",
      armorDamage: "66"
    },
    {
      ammo: "7.62x54R 7N1 Sniper cartridge",
      weight: "0.024",
      price: "238",
      damage: "86",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "45",
      projectileCount: "1",
      projectileSpeed: "875",
      penetrationChance: "0.77",
      ricochetChance: "0.285",
      fragmentationChance: "0.083",
      armorDamage: "84"
    },
    {
      ammo: "7.62x54R LPS Gzh",
      weight: "0.024",
      price: "172",
      damage: "81",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "42",
      projectileCount: "1",
      projectileSpeed: "865",
      penetrationChance: "0.76",
      ricochetChance: "0.39",
      fragmentationChance: "0.18",
      armorDamage: "78"
    },
    {
      ammo: "7.62x54R SNB",
      weight: "0.024",
      price: "375",
      damage: "75",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "62",
      projectileCount: "1",
      projectileSpeed: "875",
      penetrationChance: "0.84",
      ricochetChance: "0.285",
      fragmentationChance: "0.08",
      armorDamage: "87"
    },
    {
      ammo: "9x18mm PM 9 BZT gzh",
      weight: "0.01",
      price: "65",
      damage: "55",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "16",
      projectileCount: "1",
      projectileSpeed: "325",
      penetrationChance: "0.11",
      ricochetChance: "0.095",
      fragmentationChance: "0.17",
      armorDamage: "28"
    },
    {
      ammo: "9x18mm PM PBM",
      weight: "0.007",
      price: "71",
      damage: "44",
      accuracy: "0",
      recoil: "4",
      penetrationValue: "22",
      projectileCount: "1",
      projectileSpeed: "519",
      penetrationChance: "0.12",
      ricochetChance: "0.09",
      fragmentationChance: "0.16",
      armorDamage: "30"
    },
    {
      ammo: "9x18mm PM PMM",
      weight: "0.009",
      price: "115",
      damage: "56",
      accuracy: "0",
      recoil: "5",
      penetrationValue: "25",
      projectileCount: "1",
      projectileSpeed: "420",
      penetrationChance: "0.11",
      ricochetChance: "0.075",
      fragmentationChance: "0.17",
      armorDamage: "33"
    },
    {
      ammo: "9x18mm PM PPe gzh",
      weight: "0.009",
      price: "51",
      damage: "61",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "7",
      projectileCount: "1",
      projectileSpeed: "297",
      penetrationChance: "0.08",
      ricochetChance: "0.05",
      fragmentationChance: "0.35",
      armorDamage: "15"
    },
    {
      ammo: "9x18mm PM PPT gzh",
      weight: "0.01",
      price: "43",
      damage: "59",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "8",
      projectileCount: "1",
      projectileSpeed: "301",
      penetrationChance: "0.09",
      ricochetChance: "0.1",
      fragmentationChance: "0.166",
      armorDamage: "22"
    },
    {
      ammo: "9x18mm PM PRS gs",
      weight: "0.011",
      price: "39",
      damage: "58",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "6",
      projectileCount: "1",
      projectileSpeed: "302",
      penetrationChance: "0.085",
      ricochetChance: "0.005",
      fragmentationChance: "0.3",
      armorDamage: "16"
    },
    {
      ammo: "9x18mm PM PSO gzh",
      weight: "0.008",
      price: "22",
      damage: "54",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "5",
      projectileCount: "1",
      projectileSpeed: "315",
      penetrationChance: "0.085",
      ricochetChance: "0.065",
      fragmentationChance: "0.35",
      armorDamage: "13"
    },
    {
      ammo: "9x18mm PM Pst gzh",
      weight: "0.01",
      price: "45",
      damage: "50",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "12",
      projectileCount: "1",
      projectileSpeed: "298",
      penetrationChance: "0.1",
      ricochetChance: "0.1",
      fragmentationChance: "0.2",
      armorDamage: "26"
    },
    {
      ammo: "9x18mm PM PSV",
      weight: "0.012",
      price: "69",
      damage: "69",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "3",
      projectileCount: "1",
      projectileSpeed: "280",
      penetrationChance: "0.05",
      ricochetChance: "0.01",
      fragmentationChance: "0.4",
      armorDamage: "5"
    },
    {
      ammo: "9x18mm PM PS gs PPO",
      weight: "0.01",
      price: "29",
      damage: "55",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "6",
      projectileCount: "1",
      projectileSpeed: "330",
      penetrationChance: "0.085",
      ricochetChance: "0.03",
      fragmentationChance: "0.25",
      armorDamage: "16"
    },
    {
      ammo: "9x18mm PM 9 P gzh",
      weight: "0.011",
      price: "12",
      damage: "50",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "5",
      projectileCount: "1",
      projectileSpeed: "302",
      penetrationChance: "0.085",
      ricochetChance: "0.065",
      fragmentationChance: "0.25",
      armorDamage: "16"
    },
    {
      ammo: "9x18mm PM RG028 gzh",
      weight: "0.011",
      price: "78",
      damage: "65",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "13",
      projectileCount: "1",
      projectileSpeed: "330",
      penetrationChance: "0.1",
      ricochetChance: "0.05",
      fragmentationChance: "0.02",
      armorDamage: "26"
    },
    {
      ammo: "9x18mm PM SP7 gzh",
      weight: "0.011",
      price: "97",
      damage: "77",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "2",
      projectileCount: "1",
      projectileSpeed: "420",
      penetrationChance: "0.1",
      ricochetChance: "0.05",
      fragmentationChance: "0.02",
      armorDamage: "5"
    },
    {
      ammo: "9x18mm PM SP8 gzh",
      weight: "0.009",
      price: "45",
      damage: "67",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "1",
      projectileCount: "1",
      projectileSpeed: "250",
      penetrationChance: "0.01",
      ricochetChance: "0.05",
      fragmentationChance: "0.6",
      armorDamage: "2"
    },
    {
      ammo: "9x19mm Green Tracer",
      weight: "0.006",
      price: "72",
      damage: "58",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "14",
      projectileCount: "1",
      projectileSpeed: "365",
      penetrationChance: "0.2",
      ricochetChance: "0.05",
      fragmentationChance: "0.15",
      armorDamage: "33"
    },
    {
      ammo: "9x19mm PSO gzh",
      weight: "0.01",
      price: "49",
      damage: "56",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "10",
      projectileCount: "1",
      projectileSpeed: "340",
      penetrationChance: "0.17",
      ricochetChance: "0.065",
      fragmentationChance: "0.25",
      armorDamage: "32"
    },
    {
      ammo: "9x19mm Pst gzh",
      weight: "0.005",
      price: "62",
      damage: "54",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "18",
      projectileCount: "1",
      projectileSpeed: "457",
      penetrationChance: "0.2",
      ricochetChance: "0.05",
      fragmentationChance: "0.15",
      armorDamage: "33"
    },
    {
      ammo: "9x19mm AP 6.3",
      weight: "0.009",
      price: "110",
      damage: "52",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "25",
      projectileCount: "1",
      projectileSpeed: "392",
      penetrationChance: "0.4",
      ricochetChance: "0.2",
      fragmentationChance: "0.05",
      armorDamage: "48"
    },
    {
      ammo: "9x19mm Luger CCI",
      weight: "0.015",
      price: "185",
      damage: "70",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "10",
      projectileCount: "1",
      projectileSpeed: "420",
      penetrationChance: "0.12",
      ricochetChance: "0.065",
      fragmentationChance: "0.25",
      armorDamage: "38"
    },
    {
      ammo: "9x19mm RIP",
      weight: "0.013",
      price: "385",
      damage: "102",
      accuracy: "0",
      recoil: "20",
      penetrationValue: "2",
      projectileCount: "1",
      projectileSpeed: "381",
      penetrationChance: "0.02",
      ricochetChance: "0.002",
      fragmentationChance: "1",
      armorDamage: "11"
    },
    {
      ammo: "9x21mm SP10",
      weight: "0.023",
      price: "140",
      damage: "45",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "30",
      projectileCount: "1",
      projectileSpeed: "410",
      penetrationChance: "0.6",
      ricochetChance: "0.4",
      fragmentationChance: "0.2",
      armorDamage: "46"
    },
    {
      ammo: "9x21mm SP11",
      weight: "0.023",
      price: "150",
      damage: "66",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "15",
      projectileCount: "1",
      projectileSpeed: "413",
      penetrationChance: "0.3",
      ricochetChance: "0.2",
      fragmentationChance: "0.3",
      armorDamage: "44"
    },
    {
      ammo: "9x21mm SP12",
      weight: "0.023",
      price: "197",
      damage: "72",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "12",
      projectileCount: "1",
      projectileSpeed: "415",
      penetrationChance: "0.4",
      ricochetChance: "0.2",
      fragmentationChance: "0.35",
      armorDamage: "63"
    },
    {
      ammo: "9x21mm SP13",
      weight: "0.023",
      price: "241",
      damage: "58",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "33",
      projectileCount: "1",
      projectileSpeed: "397",
      penetrationChance: "0.6",
      ricochetChance: "0.4",
      fragmentationChance: "0.2",
      armorDamage: "47"
    },
    {
      ammo: "9x39mm 7N12 BP",
      weight: "0.023",
      price: "302",
      damage: "60",
      accuracy: "15",
      recoil: "3",
      penetrationValue: "44",
      projectileCount: "1",
      projectileSpeed: "295",
      penetrationChance: "0.75",
      ricochetChance: "0.5",
      fragmentationChance: "0.1",
      armorDamage: "68"
    },
    {
      ammo: "9x39mm SP-5",
      weight: "0.023",
      price: "160",
      damage: "68",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "30",
      projectileCount: "1",
      projectileSpeed: "290",
      penetrationChance: "0.6",
      ricochetChance: "0.4",
      fragmentationChance: "0.2",
      armorDamage: "52"
    },
    {
      ammo: "9x39mm SP-6",
      weight: "0.023",
      price: "215",
      damage: "58",
      accuracy: "0",
      recoil: "0",
      penetrationValue: "38",
      projectileCount: "1",
      projectileSpeed: "305",
      penetrationChance: "0.7",
      ricochetChance: "0.5",
      fragmentationChance: "0.1",
      armorDamage: "60"
    },
    {
      ammo: "9x39mm 7N9 SPP",
      weight: "0.023",
      price: "289",
      damage: "67",
      accuracy: "10",
      recoil: "5",
      penetrationValue: "38",
      projectileCount: "1",
      projectileSpeed: "310",
      penetrationChance: "0.6",
      ricochetChance: "0.4",
      fragmentationChance: "0.2",
      armorDamage: "56"
    }
  ];
}
</script>

<style lang="stylus">
table tbody tr td.text-start
  font-weight bold

.ammo-title
  font-weight bold

.patch-version
  color red
</style>
